version: '3'

services:
    web:
      container_name: gym
      restart: always
      build: .
      ports:
          - "3000:3000"
      links:
          - postgres
    postgres:
      container_name: postgres
      image: postgres
      ports:
          - "5432:5432"

          