name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  on-success:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile 